workflows: Pin the kubectl version used with EKS workflows
The new kubectl version v1.24.0 started causing issues with the aws-cli
tooling:
  error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

This fixes the problem by downgrading kubectl to pinned version v1.23.6 until
the issue has been fixed upstream.

Upstream issue: https://github.com/aws/aws-cli/issues/6920

Signed-off-by: Jussi Maki <jussi@isovalent.com>